spring.application.name=sistema-contador

# AZURE POSTGRESQL
spring.datasource.url=jdbc:postgresql://postgres-sistema-contador.postgres.database.azure.com:5432/accounting_system?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=WILLYvilca#10
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=${PORT:8080}

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.thymeleaf.cache=false