name: 04 - Deploy to Azure

on:
  workflow_run:
    workflows: ["03 - Package Application"]
    types:
      - completed

jobs:

  deploy:

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build project
        run: mvn clean package -DskipTests

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: sistema-contador
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: target/*.jar
